### ISSUE TITLE
Getting rid of tabs?

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#20]
We should reconsider the use of tabs for Hydraulic configs, Gaugings, RCs etc.
- They are not necessary since using the explorer on the left serves the same purpose
- I'm not sure they are useful: I don't really see a situation where tabs are more convenient than the explorer (but I may be wrong)
- They may be confusing: it's not clear when you click on e.g. a RC tab which of the existing RC's is going to be shown.
- The implementation of how panels and plots are redrawn when clicking a tab might be buggy

So getting rid of tabs might simplify code and ergonomics with no loss of functionality as far as I can see. However maybe some users are used to tabs and are in fact using them regularly? Maybe we should ask them? (poll on baratin.users, for this and possibly other changes we're not sure of?)

**Comment by IvanHeriver** [comment]
I fully agree with this. Not sure a poll is a good option though. Even if some users use the tab system, I think it should be removed since it brings too much confusion. Instead of the tab, a clear "title" would be enough. 

Isn't this issue somewhat related to issue #17?  It is about the ergonomics of BaRatinAGE. The question of how the user should navigate within BaRatinAGE (current issue) could be addressed alongside communicating in a clear way the dependencies of children (posterior rating curve or streamflow time series) to their parents (gaugings, hydraulic config, stage time series, mcmc conf, etc.)...

**Comment by IvanHeriver** [comment]
BaRatinAGE v3 does not use tab for navigating the different components. Closing the issue.
