### ISSUE TITLE
Define study name and write it somewhere

### ISSUE THREAD

**Issue by benRenard** [BaRatin-tools/BaRatinAGE#35]
original: Nom étude affichée en haut
ou ailleurs sur la fenêtre (ce serait pratique pour se repérer, avec le chemin du bar.zip aussi si possible)

**Comment by IvanHeriver** [comment]
I think this is important indeed. When testing BaRatinAGE I often want to know which file I'm currently working with since I often play with a lot of different studies... The easy (and maybe best solution) is to add this information in the main window title bar. 

For example , with a file `/home/to/some/project.bar.zip`, when open in BaRatinAGE, the window title bar could be one of the following options:
1. `BaRatinAGE - project`
2. `BaRatinAGE - /home/to/some/project.bar.zip`
3. `BaRatinAGE - project - /home/to/some/project.bar.zip`

**Comment by IvanHeriver** [comment]
fixed in BaRatinAGE v3 using the title bar approach described above.
