### ISSUE TITLE
Pb d'ouverture d'étude créées v2-1 avec la v2-2

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#4]
J'ai noté plusieurs cas d'études créées avec la 2-1 qui posent pb à l'ouverture avec la 2-2, voici deux exemples ici : https://filesender.renater.fr/?s=download&token=ba9d9035-81c2-496e-a773-aec80668441e

**Comment by IvanHeriver** [comment]
I was too late to download these examples... Could you please upload theme again?

**Comment by IvanHeriver** [comment]
I found a way to fix this bug... But  it's a temp fix which calls for further code refactoring (for BaRatinAGE v3).

As always, this bug is due to encoding issues with files within the broken project (bar zip file) which are encoded in WINDOWS-1252 instead of UTF-8.

I now use another external library called [ juniversalchardet](https://github.com/albfernandez/juniversalchardet)  which detects the file encoding so the appropriate charset can be used when creating the Scanner objects used to actually read the text files... 

Here is an idea for future development: all read/write of text files within BaRatinAGE should be centralized in a single place. 

I leave the issue open for now, waiting for feedback on this bug fix.

**Comment by JeromeLeCoz** [comment]
Great you have understood and found a way to fix it. I think it can wait for version 2-3 indeed.
