### ISSUE TITLE
Abkhaze au lieu d'Arabe

### ISSUE THREAD

**Issue by JeromeLeCoz** [BaRatin-tools/BaRatinAGE#54]
Dans les 6 premières langues (OMM), il y a cette erreur à corriger... Roger Moussa m'a par ailleurs expliqué qu'il était quasi impossible d'établir une version en arabe, cette langue n'étant pas utilisée pour ce domaine technique...

**Comment by IvanHeriver** [comment]
Indeed the code "ab" used is for abkhazen not arabic. "ar" should be used. (see [https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes).

The issue with arabic translations, is it simply the language name that appears in the list Options >Change Languages? Or are all the translations incorrects?

You mention translations into arabic is almost impossible because the language is never used this particular technical field (hydrometry). Should we keep it then?

**Comment by JeromeLeCoz** [comment]
it is simply the language name that appears in the list Options >Change Languages

The translation seems to be in Arabic (I can't read Arabic...).

Yes, we can keep it (at least because Arabic is one of the 6 official languages of WMO). All the Arabic speakers told me that the common sentences were OK. The problem seems to be able to translate technical terms like RC, gaugings, etc. that may have no equivalent in Arabic. Perhaps we'll find someone able to provide translations in the future. Let's keep it as is.

**Comment by IvanHeriver** [comment]
I corrected the language key. I think we can close the issue.
